// Code generated by ent, DO NOT EDIT.

package privatechat

import (
	"moments/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// FirstUserID applies equality check predicate on the "first_user_id" field. It's identical to FirstUserIDEQ.
func FirstUserID(v int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFirstUserID), v))
	})
}

// SecondUserID applies equality check predicate on the "second_user_id" field. It's identical to SecondUserIDEQ.
func SecondUserID(v int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSecondUserID), v))
	})
}

// FirstUserIDEQ applies the EQ predicate on the "first_user_id" field.
func FirstUserIDEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldFirstUserID), v))
	})
}

// FirstUserIDNEQ applies the NEQ predicate on the "first_user_id" field.
func FirstUserIDNEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldFirstUserID), v))
	})
}

// FirstUserIDIn applies the In predicate on the "first_user_id" field.
func FirstUserIDIn(vs ...int) predicate.PrivateChat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PrivateChat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldFirstUserID), v...))
	})
}

// FirstUserIDNotIn applies the NotIn predicate on the "first_user_id" field.
func FirstUserIDNotIn(vs ...int) predicate.PrivateChat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PrivateChat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldFirstUserID), v...))
	})
}

// FirstUserIDIsNil applies the IsNil predicate on the "first_user_id" field.
func FirstUserIDIsNil() predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldFirstUserID)))
	})
}

// FirstUserIDNotNil applies the NotNil predicate on the "first_user_id" field.
func FirstUserIDNotNil() predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldFirstUserID)))
	})
}

// SecondUserIDEQ applies the EQ predicate on the "second_user_id" field.
func SecondUserIDEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSecondUserID), v))
	})
}

// SecondUserIDNEQ applies the NEQ predicate on the "second_user_id" field.
func SecondUserIDNEQ(v int) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSecondUserID), v))
	})
}

// SecondUserIDIn applies the In predicate on the "second_user_id" field.
func SecondUserIDIn(vs ...int) predicate.PrivateChat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PrivateChat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSecondUserID), v...))
	})
}

// SecondUserIDNotIn applies the NotIn predicate on the "second_user_id" field.
func SecondUserIDNotIn(vs ...int) predicate.PrivateChat {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.PrivateChat(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSecondUserID), v...))
	})
}

// SecondUserIDIsNil applies the IsNil predicate on the "second_user_id" field.
func SecondUserIDIsNil() predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldSecondUserID)))
	})
}

// SecondUserIDNotNil applies the NotNil predicate on the "second_user_id" field.
func SecondUserIDNotNil() predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldSecondUserID)))
	})
}

// HasFirstUser applies the HasEdge predicate on the "first_user" edge.
func HasFirstUser() predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FirstUserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FirstUserTable, FirstUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFirstUserWith applies the HasEdge predicate on the "first_user" edge with a given conditions (other predicates).
func HasFirstUserWith(preds ...predicate.User) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(FirstUserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FirstUserTable, FirstUserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSecondUser applies the HasEdge predicate on the "second_user" edge.
func HasSecondUser() predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SecondUserTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SecondUserTable, SecondUserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSecondUserWith applies the HasEdge predicate on the "second_user" edge with a given conditions (other predicates).
func HasSecondUserWith(preds ...predicate.User) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(SecondUserInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SecondUserTable, SecondUserColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PrivateChat) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PrivateChat) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PrivateChat) predicate.PrivateChat {
	return predicate.PrivateChat(func(s *sql.Selector) {
		p(s.Not())
	})
}
