// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"moments/ent/channelpost"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// ChannelPost is the model entity for the ChannelPost schema.
type ChannelPost struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelPost) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelpost.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ChannelPost", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelPost fields.
func (cp *ChannelPost) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelpost.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cp.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this ChannelPost.
// Note that you need to call ChannelPost.Unwrap() before calling this method if this ChannelPost
// was returned from a transaction, and the transaction was committed or rolled back.
func (cp *ChannelPost) Update() *ChannelPostUpdateOne {
	return (&ChannelPostClient{config: cp.config}).UpdateOne(cp)
}

// Unwrap unwraps the ChannelPost entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cp *ChannelPost) Unwrap() *ChannelPost {
	_tx, ok := cp.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelPost is not a transactional entity")
	}
	cp.config.driver = _tx.drv
	return cp
}

// String implements the fmt.Stringer.
func (cp *ChannelPost) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelPost(")
	builder.WriteString(fmt.Sprintf("id=%v", cp.ID))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelPosts is a parsable slice of ChannelPost.
type ChannelPosts []*ChannelPost

func (cp ChannelPosts) config(cfg config) {
	for _i := range cp {
		cp[_i].config = cfg
	}
}
