// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"moments/ent/message"
	"moments/ent/predicate"
	"moments/ent/privatechat"
	"moments/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetCreatedDate sets the "created_date" field.
func (mu *MessageUpdate) SetCreatedDate(t time.Time) *MessageUpdate {
	mu.mutation.SetCreatedDate(t)
	return mu
}

// SetNillableCreatedDate sets the "created_date" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableCreatedDate(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetCreatedDate(*t)
	}
	return mu
}

// SetUpdatedDate sets the "updated_date" field.
func (mu *MessageUpdate) SetUpdatedDate(t time.Time) *MessageUpdate {
	mu.mutation.SetUpdatedDate(t)
	return mu
}

// SetNillableUpdatedDate sets the "updated_date" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableUpdatedDate(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetUpdatedDate(*t)
	}
	return mu
}

// SetDeletedDate sets the "deleted_date" field.
func (mu *MessageUpdate) SetDeletedDate(t time.Time) *MessageUpdate {
	mu.mutation.SetDeletedDate(t)
	return mu
}

// SetNillableDeletedDate sets the "deleted_date" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableDeletedDate(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetDeletedDate(*t)
	}
	return mu
}

// ClearDeletedDate clears the value of the "deleted_date" field.
func (mu *MessageUpdate) ClearDeletedDate() *MessageUpdate {
	mu.mutation.ClearDeletedDate()
	return mu
}

// SetPlainText sets the "plain_text" field.
func (mu *MessageUpdate) SetPlainText(s string) *MessageUpdate {
	mu.mutation.SetPlainText(s)
	return mu
}

// SetPrivateChatID sets the "private_chat" edge to the PrivateChat entity by ID.
func (mu *MessageUpdate) SetPrivateChatID(id int) *MessageUpdate {
	mu.mutation.SetPrivateChatID(id)
	return mu
}

// SetNillablePrivateChatID sets the "private_chat" edge to the PrivateChat entity by ID if the given value is not nil.
func (mu *MessageUpdate) SetNillablePrivateChatID(id *int) *MessageUpdate {
	if id != nil {
		mu = mu.SetPrivateChatID(*id)
	}
	return mu
}

// SetPrivateChat sets the "private_chat" edge to the PrivateChat entity.
func (mu *MessageUpdate) SetPrivateChat(p *PrivateChat) *MessageUpdate {
	return mu.SetPrivateChatID(p.ID)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (mu *MessageUpdate) SetOwnerID(id int) *MessageUpdate {
	mu.mutation.SetOwnerID(id)
	return mu
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (mu *MessageUpdate) SetNillableOwnerID(id *int) *MessageUpdate {
	if id != nil {
		mu = mu.SetOwnerID(*id)
	}
	return mu
}

// SetOwner sets the "owner" edge to the User entity.
func (mu *MessageUpdate) SetOwner(u *User) *MessageUpdate {
	return mu.SetOwnerID(u.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearPrivateChat clears the "private_chat" edge to the PrivateChat entity.
func (mu *MessageUpdate) ClearPrivateChat() *MessageUpdate {
	mu.mutation.ClearPrivateChat()
	return mu
}

// ClearOwner clears the "owner" edge to the User entity.
func (mu *MessageUpdate) ClearOwner() *MessageUpdate {
	mu.mutation.ClearOwner()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(mu.hooks) == 0 {
		if err = mu.check(); err != nil {
			return 0, err
		}
		affected, err = mu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = mu.check(); err != nil {
				return 0, err
			}
			mu.mutation = mutation
			affected, err = mu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(mu.hooks) - 1; i >= 0; i-- {
			if mu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = mu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, mu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.PlainText(); ok {
		if err := message.PlainTextValidator(v); err != nil {
			return &ValidationError{Name: "plain_text", err: fmt.Errorf(`ent: validator failed for field "Message.plain_text": %w`, err)}
		}
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   message.Table,
			Columns: message.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: message.FieldID,
			},
		},
	}
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.CreatedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: message.FieldCreatedDate,
		})
	}
	if value, ok := mu.mutation.UpdatedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: message.FieldUpdatedDate,
		})
	}
	if value, ok := mu.mutation.DeletedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: message.FieldDeletedDate,
		})
	}
	if mu.mutation.DeletedDateCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: message.FieldDeletedDate,
		})
	}
	if value, ok := mu.mutation.PlainText(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: message.FieldPlainText,
		})
	}
	if mu.mutation.PrivateChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.PrivateChatTable,
			Columns: []string{message.PrivateChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: privatechat.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.PrivateChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.PrivateChatTable,
			Columns: []string{message.PrivateChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: privatechat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.OwnerTable,
			Columns: []string{message.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.OwnerTable,
			Columns: []string{message.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetCreatedDate sets the "created_date" field.
func (muo *MessageUpdateOne) SetCreatedDate(t time.Time) *MessageUpdateOne {
	muo.mutation.SetCreatedDate(t)
	return muo
}

// SetNillableCreatedDate sets the "created_date" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableCreatedDate(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetCreatedDate(*t)
	}
	return muo
}

// SetUpdatedDate sets the "updated_date" field.
func (muo *MessageUpdateOne) SetUpdatedDate(t time.Time) *MessageUpdateOne {
	muo.mutation.SetUpdatedDate(t)
	return muo
}

// SetNillableUpdatedDate sets the "updated_date" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableUpdatedDate(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetUpdatedDate(*t)
	}
	return muo
}

// SetDeletedDate sets the "deleted_date" field.
func (muo *MessageUpdateOne) SetDeletedDate(t time.Time) *MessageUpdateOne {
	muo.mutation.SetDeletedDate(t)
	return muo
}

// SetNillableDeletedDate sets the "deleted_date" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableDeletedDate(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetDeletedDate(*t)
	}
	return muo
}

// ClearDeletedDate clears the value of the "deleted_date" field.
func (muo *MessageUpdateOne) ClearDeletedDate() *MessageUpdateOne {
	muo.mutation.ClearDeletedDate()
	return muo
}

// SetPlainText sets the "plain_text" field.
func (muo *MessageUpdateOne) SetPlainText(s string) *MessageUpdateOne {
	muo.mutation.SetPlainText(s)
	return muo
}

// SetPrivateChatID sets the "private_chat" edge to the PrivateChat entity by ID.
func (muo *MessageUpdateOne) SetPrivateChatID(id int) *MessageUpdateOne {
	muo.mutation.SetPrivateChatID(id)
	return muo
}

// SetNillablePrivateChatID sets the "private_chat" edge to the PrivateChat entity by ID if the given value is not nil.
func (muo *MessageUpdateOne) SetNillablePrivateChatID(id *int) *MessageUpdateOne {
	if id != nil {
		muo = muo.SetPrivateChatID(*id)
	}
	return muo
}

// SetPrivateChat sets the "private_chat" edge to the PrivateChat entity.
func (muo *MessageUpdateOne) SetPrivateChat(p *PrivateChat) *MessageUpdateOne {
	return muo.SetPrivateChatID(p.ID)
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (muo *MessageUpdateOne) SetOwnerID(id int) *MessageUpdateOne {
	muo.mutation.SetOwnerID(id)
	return muo
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableOwnerID(id *int) *MessageUpdateOne {
	if id != nil {
		muo = muo.SetOwnerID(*id)
	}
	return muo
}

// SetOwner sets the "owner" edge to the User entity.
func (muo *MessageUpdateOne) SetOwner(u *User) *MessageUpdateOne {
	return muo.SetOwnerID(u.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearPrivateChat clears the "private_chat" edge to the PrivateChat entity.
func (muo *MessageUpdateOne) ClearPrivateChat() *MessageUpdateOne {
	muo.mutation.ClearPrivateChat()
	return muo
}

// ClearOwner clears the "owner" edge to the User entity.
func (muo *MessageUpdateOne) ClearOwner() *MessageUpdateOne {
	muo.mutation.ClearOwner()
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	var (
		err  error
		node *Message
	)
	if len(muo.hooks) == 0 {
		if err = muo.check(); err != nil {
			return nil, err
		}
		node, err = muo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*MessageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = muo.check(); err != nil {
				return nil, err
			}
			muo.mutation = mutation
			node, err = muo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(muo.hooks) - 1; i >= 0; i-- {
			if muo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = muo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, muo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Message)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from MessageMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.PlainText(); ok {
		if err := message.PlainTextValidator(v); err != nil {
			return &ValidationError{Name: "plain_text", err: fmt.Errorf(`ent: validator failed for field "Message.plain_text": %w`, err)}
		}
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   message.Table,
			Columns: message.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: message.FieldID,
			},
		},
	}
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.CreatedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: message.FieldCreatedDate,
		})
	}
	if value, ok := muo.mutation.UpdatedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: message.FieldUpdatedDate,
		})
	}
	if value, ok := muo.mutation.DeletedDate(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: message.FieldDeletedDate,
		})
	}
	if muo.mutation.DeletedDateCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: message.FieldDeletedDate,
		})
	}
	if value, ok := muo.mutation.PlainText(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: message.FieldPlainText,
		})
	}
	if muo.mutation.PrivateChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.PrivateChatTable,
			Columns: []string{message.PrivateChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: privatechat.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.PrivateChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.PrivateChatTable,
			Columns: []string{message.PrivateChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: privatechat.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.OwnerTable,
			Columns: []string{message.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.OwnerTable,
			Columns: []string{message.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
