// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"moments/ent/predicate"
	"moments/ent/privatechat"
	"moments/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PrivateChatQuery is the builder for querying PrivateChat entities.
type PrivateChatQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PrivateChat
	// eager-loading edges.
	withFirstUser  *UserQuery
	withSecondUser *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PrivateChatQuery builder.
func (pcq *PrivateChatQuery) Where(ps ...predicate.PrivateChat) *PrivateChatQuery {
	pcq.predicates = append(pcq.predicates, ps...)
	return pcq
}

// Limit adds a limit step to the query.
func (pcq *PrivateChatQuery) Limit(limit int) *PrivateChatQuery {
	pcq.limit = &limit
	return pcq
}

// Offset adds an offset step to the query.
func (pcq *PrivateChatQuery) Offset(offset int) *PrivateChatQuery {
	pcq.offset = &offset
	return pcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pcq *PrivateChatQuery) Unique(unique bool) *PrivateChatQuery {
	pcq.unique = &unique
	return pcq
}

// Order adds an order step to the query.
func (pcq *PrivateChatQuery) Order(o ...OrderFunc) *PrivateChatQuery {
	pcq.order = append(pcq.order, o...)
	return pcq
}

// QueryFirstUser chains the current query on the "first_user" edge.
func (pcq *PrivateChatQuery) QueryFirstUser() *UserQuery {
	query := &UserQuery{config: pcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(privatechat.Table, privatechat.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, privatechat.FirstUserTable, privatechat.FirstUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(pcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySecondUser chains the current query on the "second_user" edge.
func (pcq *PrivateChatQuery) QuerySecondUser() *UserQuery {
	query := &UserQuery{config: pcq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(privatechat.Table, privatechat.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, privatechat.SecondUserTable, privatechat.SecondUserColumn),
		)
		fromU = sqlgraph.SetNeighbors(pcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PrivateChat entity from the query.
// Returns a *NotFoundError when no PrivateChat was found.
func (pcq *PrivateChatQuery) First(ctx context.Context) (*PrivateChat, error) {
	nodes, err := pcq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{privatechat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pcq *PrivateChatQuery) FirstX(ctx context.Context) *PrivateChat {
	node, err := pcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PrivateChat ID from the query.
// Returns a *NotFoundError when no PrivateChat ID was found.
func (pcq *PrivateChatQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{privatechat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pcq *PrivateChatQuery) FirstIDX(ctx context.Context) int {
	id, err := pcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PrivateChat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PrivateChat entity is found.
// Returns a *NotFoundError when no PrivateChat entities are found.
func (pcq *PrivateChatQuery) Only(ctx context.Context) (*PrivateChat, error) {
	nodes, err := pcq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{privatechat.Label}
	default:
		return nil, &NotSingularError{privatechat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pcq *PrivateChatQuery) OnlyX(ctx context.Context) *PrivateChat {
	node, err := pcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PrivateChat ID in the query.
// Returns a *NotSingularError when more than one PrivateChat ID is found.
// Returns a *NotFoundError when no entities are found.
func (pcq *PrivateChatQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = pcq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{privatechat.Label}
	default:
		err = &NotSingularError{privatechat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pcq *PrivateChatQuery) OnlyIDX(ctx context.Context) int {
	id, err := pcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PrivateChats.
func (pcq *PrivateChatQuery) All(ctx context.Context) ([]*PrivateChat, error) {
	if err := pcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pcq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pcq *PrivateChatQuery) AllX(ctx context.Context) []*PrivateChat {
	nodes, err := pcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PrivateChat IDs.
func (pcq *PrivateChatQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := pcq.Select(privatechat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pcq *PrivateChatQuery) IDsX(ctx context.Context) []int {
	ids, err := pcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pcq *PrivateChatQuery) Count(ctx context.Context) (int, error) {
	if err := pcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pcq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pcq *PrivateChatQuery) CountX(ctx context.Context) int {
	count, err := pcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pcq *PrivateChatQuery) Exist(ctx context.Context) (bool, error) {
	if err := pcq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pcq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pcq *PrivateChatQuery) ExistX(ctx context.Context) bool {
	exist, err := pcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PrivateChatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pcq *PrivateChatQuery) Clone() *PrivateChatQuery {
	if pcq == nil {
		return nil
	}
	return &PrivateChatQuery{
		config:         pcq.config,
		limit:          pcq.limit,
		offset:         pcq.offset,
		order:          append([]OrderFunc{}, pcq.order...),
		predicates:     append([]predicate.PrivateChat{}, pcq.predicates...),
		withFirstUser:  pcq.withFirstUser.Clone(),
		withSecondUser: pcq.withSecondUser.Clone(),
		// clone intermediate query.
		sql:    pcq.sql.Clone(),
		path:   pcq.path,
		unique: pcq.unique,
	}
}

// WithFirstUser tells the query-builder to eager-load the nodes that are connected to
// the "first_user" edge. The optional arguments are used to configure the query builder of the edge.
func (pcq *PrivateChatQuery) WithFirstUser(opts ...func(*UserQuery)) *PrivateChatQuery {
	query := &UserQuery{config: pcq.config}
	for _, opt := range opts {
		opt(query)
	}
	pcq.withFirstUser = query
	return pcq
}

// WithSecondUser tells the query-builder to eager-load the nodes that are connected to
// the "second_user" edge. The optional arguments are used to configure the query builder of the edge.
func (pcq *PrivateChatQuery) WithSecondUser(opts ...func(*UserQuery)) *PrivateChatQuery {
	query := &UserQuery{config: pcq.config}
	for _, opt := range opts {
		opt(query)
	}
	pcq.withSecondUser = query
	return pcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FirstUserID int `json:"first_user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PrivateChat.Query().
//		GroupBy(privatechat.FieldFirstUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pcq *PrivateChatQuery) GroupBy(field string, fields ...string) *PrivateChatGroupBy {
	grbuild := &PrivateChatGroupBy{config: pcq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pcq.sqlQuery(ctx), nil
	}
	grbuild.label = privatechat.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FirstUserID int `json:"first_user_id,omitempty"`
//	}
//
//	client.PrivateChat.Query().
//		Select(privatechat.FieldFirstUserID).
//		Scan(ctx, &v)
//
func (pcq *PrivateChatQuery) Select(fields ...string) *PrivateChatSelect {
	pcq.fields = append(pcq.fields, fields...)
	selbuild := &PrivateChatSelect{PrivateChatQuery: pcq}
	selbuild.label = privatechat.Label
	selbuild.flds, selbuild.scan = &pcq.fields, selbuild.Scan
	return selbuild
}

func (pcq *PrivateChatQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pcq.fields {
		if !privatechat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pcq.path != nil {
		prev, err := pcq.path(ctx)
		if err != nil {
			return err
		}
		pcq.sql = prev
	}
	return nil
}

func (pcq *PrivateChatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PrivateChat, error) {
	var (
		nodes       = []*PrivateChat{}
		_spec       = pcq.querySpec()
		loadedTypes = [2]bool{
			pcq.withFirstUser != nil,
			pcq.withSecondUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*PrivateChat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &PrivateChat{config: pcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, pcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := pcq.withFirstUser; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*PrivateChat)
		for i := range nodes {
			fk := nodes[i].FirstUserID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "first_user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.FirstUser = n
			}
		}
	}

	if query := pcq.withSecondUser; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*PrivateChat)
		for i := range nodes {
			fk := nodes[i].SecondUserID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "second_user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.SecondUser = n
			}
		}
	}

	return nodes, nil
}

func (pcq *PrivateChatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pcq.querySpec()
	_spec.Node.Columns = pcq.fields
	if len(pcq.fields) > 0 {
		_spec.Unique = pcq.unique != nil && *pcq.unique
	}
	return sqlgraph.CountNodes(ctx, pcq.driver, _spec)
}

func (pcq *PrivateChatQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pcq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pcq *PrivateChatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   privatechat.Table,
			Columns: privatechat.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: privatechat.FieldID,
			},
		},
		From:   pcq.sql,
		Unique: true,
	}
	if unique := pcq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pcq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, privatechat.FieldID)
		for i := range fields {
			if fields[i] != privatechat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pcq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pcq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pcq *PrivateChatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pcq.driver.Dialect())
	t1 := builder.Table(privatechat.Table)
	columns := pcq.fields
	if len(columns) == 0 {
		columns = privatechat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pcq.sql != nil {
		selector = pcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pcq.unique != nil && *pcq.unique {
		selector.Distinct()
	}
	for _, p := range pcq.predicates {
		p(selector)
	}
	for _, p := range pcq.order {
		p(selector)
	}
	if offset := pcq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pcq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PrivateChatGroupBy is the group-by builder for PrivateChat entities.
type PrivateChatGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pcgb *PrivateChatGroupBy) Aggregate(fns ...AggregateFunc) *PrivateChatGroupBy {
	pcgb.fns = append(pcgb.fns, fns...)
	return pcgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pcgb *PrivateChatGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pcgb.path(ctx)
	if err != nil {
		return err
	}
	pcgb.sql = query
	return pcgb.sqlScan(ctx, v)
}

func (pcgb *PrivateChatGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pcgb.fields {
		if !privatechat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pcgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pcgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pcgb *PrivateChatGroupBy) sqlQuery() *sql.Selector {
	selector := pcgb.sql.Select()
	aggregation := make([]string, 0, len(pcgb.fns))
	for _, fn := range pcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pcgb.fields)+len(pcgb.fns))
		for _, f := range pcgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pcgb.fields...)...)
}

// PrivateChatSelect is the builder for selecting fields of PrivateChat entities.
type PrivateChatSelect struct {
	*PrivateChatQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pcs *PrivateChatSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pcs.prepareQuery(ctx); err != nil {
		return err
	}
	pcs.sql = pcs.PrivateChatQuery.sqlQuery(ctx)
	return pcs.sqlScan(ctx, v)
}

func (pcs *PrivateChatSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pcs.sql.Query()
	if err := pcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
