// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// ChannelPost is the predicate function for channelpost builders.
type ChannelPost func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// PrivateChat is the predicate function for privatechat builders.
type PrivateChat func(*sql.Selector)

// PublicChat is the predicate function for publicchat builders.
type PublicChat func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
