// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
