// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Channel is the predicate function for channel builders.
type Channel func(*sql.Selector)

// ChannelPost is the predicate function for channelpost builders.
type ChannelPost func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
